# Site settings
title: Sparetire's Blog
header-img: img/home-bg.jpg
email: s9ar371r3@gmail.com
description: "愿不违心"
baseurl: 
url: "http://www.spartire.me"
twitter_username: Sparetire_
github_username:  sparetire
facebook_username:  IronSummitMedia
timezone: Asia/Taipei
encoding: utf-8

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
